buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '2.3-SNAPSHOT', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'idea'

version = "${mod_version}-mc${mc_version}"
group = mod_group
archivesBaseName = mod_id

sourceCompatibility = 1.8
targetCompatibility = 1.8
compileJava.options.encoding = 'UTF-8'

minecraft {
    version = "${mc_version}-${forge_version}"
    runDir = 'run'
    mappings = mappings_version
    makeObfSourceJar = false
    replace '@MOD_VERSION@', project.mod_version
    replaceIn 'QuickCraft.java'
}

repositories {
    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
    }
}

dependencies {
    deobfCompile "curse.maven:jei-238222:${jei_file}"
    deobfCompile "curse.maven:projecte-226410:${projecte_file}"

    deobfCompile "curse.maven:applied-energistics-2-223794:${ae2_file}"
    deobfCompile "curse.maven:refined-storage-243076:${rs_file}"
    deobfCompile "curse.maven:refined-storage-addons-272302:${rs_addons_file}"
    deobfCompile "curse.maven:just-enough-resources-240630:${jer_file}"
    deobfCompile "curse.maven:codechickenlib-242818:${ccl_file}"
    deobfCompile "curse.maven:avaritia-261348:${avaritia_file}"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.mod_version, 'mcversion': mc_version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes([
                'FMLCorePluginContainsFMLMod': 'false',
                'Specification-Title'        : mod_name,
                'Specification-Vendor'       : 'Sxilverr',
                'Specification-Version'      : '1',
                'Implementation-Title'       : mod_name,
                'Implementation-Version'     : project.mod_version,
                'Implementation-Vendor'      : 'Sxilverr'
        ])
    }
}
